### ISSUE TITLE
Osquery gets config from fleet, but the config didn't work

### ISSUE THREAD

**Issue by WinMordekaiser** [osquery/osquery#6520]
# Bug report
### What operating system and version are you using?
CentOS Linux release 7.8.2003
### What version of osquery are you using?
4.3.0
### What steps did you take to reproduce the issue?
1. start fleet with this options
```
apiVersion: v1
kind: options
spec:
  config:
    decorators:
      load:
      - SELECT uuid AS host_uuid FROM system_info;
      - SELECT hostname AS hostname FROM system_info;
    options:
      config_refresh: 3
      disable_distributed: false
      distributed_interval: 10
      distributed_plugin: tls
      distributed_tls_max_attempts: 3
      logger_plugin: tls
      logger_tls_endpoint: /api/v1/osquery/log
      logger_tls_period: 10
      pack_delimiter: /
  overrides: {}
```

2. fleetctl apply -f my.yml   update the option
```
apiVersion: v1
kind: options
spec:
  config:
    decorators:
      load:
      - SELECT uuid AS host_uuid FROM system_info;
      - SELECT hostname AS hostname FROM system_info;
    options:
      config_refresh: 10
      disable_distributed: false
      distributed_interval: 10
      distributed_plugin: tls
      distributed_tls_max_attempts: 3
      logger_tls_endpoint: /api/v1/osquery/log
      logger_tls_period: 10
      pack_delimiter: /
      logger_kafka_brokers: ssl://192.168.84.130:9093
      logger_kafka_topic: test
      logger_kafka_compression: gzip
      logger_kafka_acks: 1
      logger_plugin: kafka_producer
      tls_client_cert: /usr/local/apps/kafka/pki/certificate.pem
      tls_server_certs: /usr/local/apps/kafka/pki/CARoot.pem
      tls_client_key: /usr/local/apps/kafka/pki/client-key.pem
```
3. osquery get the conf
```
I0624 09:55:19.300721 50668 config.cpp:1214] Refreshing configuration state
I0624 09:55:19.301201 50668 tls.cpp:253] TLS/HTTPS POST request to URI: https://192.168.84.129:8080/api/v1/osquery/config
{"node_key":"6PxMsFiMhRl5ByJij1UcjWM6B/ntGYfi"}
{
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT hostname AS hostname FROM system_info;"
    ]
  },
  "options": {
    "config_refresh": 10,
    "disable_distributed": false,
    "distributed_interval": 10,
    "distributed_plugin": "tls",
    "distributed_tls_max_attempts": 3,
    "logger_kafka_acks": 1,
    "logger_kafka_brokers": "ssl://192.168.84.130:9093",
    "logger_kafka_compression": "gzip",
    "logger_kafka_topic": "test",
    "logger_plugin": "kafka_producer",
    "logger_tls_endpoint": "/api/v1/osquery/log",
    "logger_tls_period": 10,
    "pack_delimiter": "/",
    "tls_client_cert": "/usr/local/apps/kafka/pki/certificate.pem",
    "tls_client_key": "/usr/local/apps/kafka/pki/client-key.pem",
    "tls_server_certs": "/usr/local/apps/kafka/pki/CARoot.pem"
  },
  "packs": {
    "linux_users_check": {
      "queries": {
        "linux_users": {
          "query": "select * from users;",
          "interval": 10,
          "snapshot": true
        }
      }
    }
  }
}
```
4. kafka didn't get any message

### What did you expect to see?
After refeshing config, kafka can get message without restart osqueryd 
### What did you see instead?
kafka didn't get message
