### ISSUE TITLE
[4.5.1] Fim detection "/%" not working

### ISSUE THREAD

**Issue by juju4** [osquery/osquery#6731]
# Bug report

### What operating system and version are you using?

        version = 18.04.5 LTS (Bionic Beaver)
          build = 
       platform = ubuntu

### What version of osquery are you using?

version = 4.5.1
(from debian osquery repository)

### What steps did you take to reproduce the issue?
From Travis-CI ansible role weekly testing

it monitors folders at root non-recursive with osquery fim (default inotify)
https://github.com/juju4/ansible-osquery/blob/master/defaults/main.yml#L107
```
  - name: root
    list:
      - "/%"
```

and we create directories/files to test detection
https://github.com/juju4/ansible-osquery/blob/master/tasks/testing.yml#L38
```
- block:
    - name: ensure directory exists
      file:
        dest: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /tmp/too_many_events
        - /tmp/too_many_events/a
        - /tmp/too_many_events/a/b
        - /tmp/too_many_events2/test
        - /tmp/too_many_events2/a
        - /tmp/too_many_events2/a/b
        - /tmp/too_many_events3/a
        - /tmp/too_many_events3/a/b
        - /tmp/excluded6-testing
        - /var/tmp/a
        - /var/tmp/a/.b
        - /var/tmp/b
        - /var/tmp/b/.c
        - /var/tmp/b/.c/d
        - /a/b/c
        - /fim-testing-dir
  when: osquery_testing_fimfiles or osquery_testing_fim_load

- block:
    - name: create files normally excluded
      file:
        name: "{{ item }}"
        state: touch
      with_items:
        - /tmp/too_many_events2/test/testing-aa
        - /tmp/too_many_events/fim-testing1
        - /tmp/too_many_events/a/fim-testing2
        - /tmp/too_many_events/a/b/fim-testing3
        - /tmp/too_many_events2/fim-testing1
        - /tmp/too_many_events2/a/fim-testing2
        - /tmp/too_many_events2/a/b/fim-testing3
        - /tmp/too_many_events3/fim-testing1
        - /tmp/too_many_events3/a/fim-testing2
        - /tmp/too_many_events3/a/b/fim-testing3
[...]
        - /var/tmp/a/fim-testing1
        - /var/tmp/a/.fim-testing2
        - /var/tmp/a/.b/fim-testing3
        - /var/tmp/b/.fim-testing4
        - /var/tmp/b/.c/fim-testing5
        - /var/tmp/b/.c/d/fim-testing6
        - /fim-testing0
        - /a/b/fim-testing10
        - /a/b/c/fim-testing11
    - name: test files
      file:
        name: "{{ item }}"
        state: touch
      with_items: "{{ osquery_testing_fim_files }}"
  when: osquery_testing_fimfiles
```

### What did you expect to see?

ok 4.4.0-1 (about 2 weeks ago)
https://travis-ci.com/github/juju4/ansible-osquery/jobs/396686389

https://travis-ci.com/github/juju4/ansible-osquery/jobs/396686389#L6065
```
      Finished in 0.4061 seconds (files took 0.4404 seconds to load)
       49 examples, 0 failures
```

### What did you see instead?

nok 4.5.1-1.linux (since about a week)
https://travis-ci.com/github/juju4/ansible-osquery/jobs/399971602 

https://travis-ci.com/github/juju4/ansible-osquery/jobs/399971602#L6006
```
       File "/var/log/osquery/osqueryd.results.log"
[...]
         is expected to contain "\"target_path\":\"\\/\\/fim-testing1" (FAILED - 1)
         is expected to contain "\"target_path\":\"\\/root\\/fim-testing2" (FAILED - 2)
[...]
         is expected to contain "\"target_path\":\"\\/\\/a" (FAILED - 3)
         is expected to contain "\"target_path\":\"\\/\\/fim-testing-dir" (FAILED - 4)
         is expected to contain "\"target_path\":\"\\/\\/fim-testing0" (FAILED - 5)
```

same on centos8 and ubuntu20.04
https://travis-ci.com/github/juju4/ansible-osquery/jobs/406817289#L7929
https://travis-ci.com/github/juju4/ansible-osquery/jobs/406817290#L6631
https://travis-ci.com/github/juju4/ansible-osquery/jobs/406817291#L6674

confirmed on ubuntu18.04 when reverting to 4.4.0
https://travis-ci.com/github/juju4/ansible-osquery/jobs/406897735#L6760
ubuntu20.04 pass all check but one (not same matching pattern) after revert
https://travis-ci.com/github/juju4/ansible-osquery/jobs/406897733#L5658
