### ISSUE TITLE
Severe disk impact and IOPS usage due to Database unexpected growth

### ISSUE THREAD

**Issue by Jimjazzz** [osquery/osquery#7079]
### What operating system and version are you using?
Windows 10.0.19042
Windows Server 2012

### What version of osquery are you using?
 - 4.8.0 
 - 4.6.0

### What steps did you take to reproduce the issue?
In a Windows system, we want to get the windows events. So we activate the event capture in osquery.flags
--disable_events=false
--enable_windows_events_subscriber=true
--enable_windows_events_publisher=true

We have 1 pack that runs two queries every 10 seconds (we tested other intervals as well 20s and 30s):
```
SELECT *, "events_windows.other_sources" || "." || eventid as __devoSubTag FROM windows_events WHERE lower(source) Not IN ('application', 'setup', 'security', 'system', 'microsoft-windows-powershell/operational', 'microsoft-windows-powershell/admin');
SELECT *, "events_windows." || lower(source) || "." || eventid as __devoSubTag FROM windows_events WHERE lower(source) IN ('application', 'setup', 'security', 'system');
```

Our typical deployment has events_max=100000 and buffered_log_max=100000. In order to flush out any buffered logs and to make sure that osquery is being able to keep up with the events load, we have set events_max=1, buffered_log_max=1 and events_expiry=10. If my understanding is correct, the config should discard events[ and logs[ right away after being queried. Following is the options we configure in the fleet side:
```
      windows:
        options:
          events_max: 1
          events_expiry: 10
          logger_plugin: tls
          config_refresh: 30
          pack_delimiter: /
          schedule_reload: 3600
          buffered_log_max: 1
          logger_min_status: 1
          logger_tls_period: 20
          tls_session_reuse: false
          distributed_plugin: tls
          disable_distributed: false
          logger_tls_endpoint: /api/v1/osquery/log
          distributed_interval: 10
          pack_refresh_interval: 3600
          watchdog_memory_limit: 512
          schedule_splay_percent: 10
          windows_event_channels: >-
            System,Application,Setup,Security,Microsoft-Windows-PowerShell/Operational,ForwardedEvents
          logger_snapshot_event_type: true
          distributed_tls_max_attempts: 3
          distributed_tls_read_endpoint: /api/v1/osquery/distributed/read
          distributed_tls_write_endpoint: /api/v1/osquery/distributed/write
```

The server is pretty busy and generates around 100 events/second. The database dump does not show a big amount of events being buffered, but still seems to be growing.

### What did you expect to see?
 - The number of SST and LOG files in osquery.db and the total size keeps in a more or less stable value, not growing. (currently a new LOG file is created every few seconds, and a SST maybe around 1-2 min)
 - IOPS stay at a reasonable level.

### What did you see instead?
- The number of sst and log files keeps growing with time, in size and number. The total space in disk also grows to near a 1 Gb in few hours. Older files are never deleted.
- Using the windows resource monitor, we see that the IOPS are very high. 

Other Info:
- Using the --disable_database , IOPS drops drastically.
- We typically use a tls endpoint to flush logs. We have set osquery to write to the filesystem and seen the same behavior.
- Doing a --database_dump shows very few information but still the size seems big. Using the sst_dump tool we can see that there is more info in the database than it seems. See the attached example:
[no-new-events-osquery.db.zip](https://github.com/osquery/osquery/files/6380832/no-new-events-osquery.db.zip)
